=== public-transport/transport-apis/schema.json
{
  "$id": "https://raw.githubusercontent.com/public-transport/transport-apis/v1/schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "public transport API description",
  "type": "object",
  "required": [
    "name",
    "type",
    "supportedLanguages",
    "coverage",
    "options"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "type": {
      "type": "object",
      "propertyNames": {
        "enum": [
          "efa",
          "hafasMgate",
          "hafasQuery",
          "navitia",
          "otpGraphQl",
          "otpRest"
        ]
      },
      "additionalProperties": {
        "type": "boolean"
      }
    },
    "supportedLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z][a-z]$",
        "description": "ISO-639-1 language code"
      }
    },
    "coverage": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "realtimeCoverage": {
          "$ref": "#/definitions/coverage"
        },
        "regularCoverage": {
          "$ref": "#/definitions/coverage"
        },
        "anyCoverage": {
          "$ref": "#/definitions/coverage"
        }
      }
    },
    "attribution": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/attribution_opendata" },
        { "$ref": "#/definitions/attribution_proprietary" }
      ]
    },
    "options": {
      "type": "object"
    }
  },
  "definitions": {
    "coverage": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "area": {
          "$ref": "#/definitions/coverage_geojson"
        },
        "region": {
          "$ref": "#/definitions/coverage_region"
        }
      }
    },
    "coverage_geojson": {
      "type": "object",
      "required": [
        "type",
        "coordinates"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Polygon"
          ]
        },
        "coordinates": {
          "type": "array",
          "items": {
            "type": "array",
            "minItems": 4,
            "items": {
              "type": "array",
              "minItems": 2,
              "items": {
                "type": "number"
              }
            }
          }
        },
        "bbox": {
          "type": "array",
          "minItems": 4,
          "items": {
            "type": "number"
          }
        }
      }
    },
    "coverage_region": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z][a-zA-Z](-[a-zA-Z][a-zA-Z])?$",
        "description": "ISO-3166-1/2 country/region code"
      },
      "minItems": 1
    },
    "attribution_opendata": {
      "type": "object",
      "required": [
        "license",
        "name"
      ],
      "properties": {
        "license": {
          "type": "string",
          "description": "Open Definition license ID or SPDX license id"
        },
        "name": {
          "type": "string"
        },
        "homepage": {
          "type": "string"
        }
      }
    },
    "attribution_proprietary": {
      "type": "object",
      "required": [
        "isProprietary"
      ],
      "properties": {
        "isProprietary": {
          "type": "boolean"
        }
      }
    }
  }
}

=== public-transport/transport-apis/data/de/vrr-efa.json
{
	"name": "Verkehrsverbund Rhein-Ruhr (VRR)",
	"type": {
		"efa": true
	},
	"coverage": {
		"realtimeCoverage": {
			"area": {
				"coordinates": [
					[ [ 5.8835, 51.9055 ], [ 6.0496, 51.111 ], [ 7.6174, 50.9833 ], [ 7.6207, 51.79 ], [ 5.8835, 51.9055 ] ]
				],
				"type": "Polygon"
			},
			"region": [ "DE-NW" ]
		}
	},
	"supportedLanguages": [
		"en",
		"de"
	],
	"options": {
		"endpoint": "https://efa.vrr.de/standard/",
		"supportedOutputFormats": [ "XML", "JSON" ],
		"xmlOutputFormat": "full"
	}
}

=== public-transport/transport-apis/data/no/entur-otp.json
{
    "name": "Entur",
    "attribution": {
        "license": "Norwegian Licence for Open Government Data (NLOD)",
        "licenseUrl": "https://data.norge.no/nlod/en",
        "name": "Entur",
        "url": "https://www.entur.org/"
    },
    "coverage": {
        "regularCoverage": {
            "area": {
                "coordinates": [ [ [ 5.14553, 58.7711 ], [ 8.5538, 56.8847 ], [ 31.5632, 69.8993 ], [ 25.3899, 85.02453 ], [ -0.1243, 75.9905 ], [ 5.14553, 58.7711 ] ] ],
                "type": "Polygon"
            },
            "region": [ "NO" ]
        }
    },
    "options": {
        "endpoint": "https://api.entur.io/journey-planner/v2/graphql/",
        "apiVersion": "entur"
    },
    "supportedLanguages": [ "no" ],
    "type": {
        "otpGraphQl": true
    }
}

=== public-transport/transport-apis/data/de/rnv-motis.json
{
  "name": "Rhein-Neckar-Verkehr (directions.nwex.de)",
  "attribution": {
    "license": "DL-DE-BY-2.0",
    "name": "Rhein-Neckar-Verkehr GmbH",
    "homepage": "https://www.opendata-oepnv.de/ht/de/organisation/verkehrsunternehmen/rnv/openrnv/datensaetze"
  },
  "type": {
    "motis": true
  },
  "options": {
    "endpoint": "https://directions.nwex.de/api/providers/rhein-neckar-verkehr/",
    "intermodal": false,
    "motisVersion": "2.10.0",
    "supportedModes": []
  },
  "supportedLanguages": [
    "de"
  ],
  "coverage": {
    "realtimeCoverage": {
      "region": [
        "DE-HE",
        "DE-BW",
        "DE-RP"
      ],
      "area": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              8.661474836362174,
              49.56682199364306
            ],
            [
              8.646425409204426,
              49.55683827153436
            ],
            [
              8.610426565970243,
              49.55030846609782
            ],
            [
              8.581968164292903,
              49.557772522235695
            ],
            [
              8.556351727249393,
              49.54875631214381
            ],
            [
              8.548812334394682,
              49.52482309287569
            ],
            [
              8.532768217291789,
              49.536837593048006
            ],
            [
              8.49568358055447,
              49.57276908058989
            ],
            [
              8.47596243926148,
              49.58486398998741
            ],
            [
              8.446148018713984,
              49.5910126926984
            ],
            [
              8.421984047133833,
              49.584234219227056
            ],
            [
              8.417369892833676,
              49.54875631214381
            ],
            [
              8.403460359038036,
              49.54521297867433
            ],
            [
              8.371147309501254,
              49.55540685393504
            ],
            [
              8.332861202489909,
              49.55297903280126
            ],
            [
              8.331376934216394,
              49.53757185617485
            ],
            [
              8.334943345489364,
              49.5221286699925
            ],
            [
              8.336906777951043,
              49.49889644661647
            ],
            [
              8.306780420645339,
              49.488550059089164
            ],
            [
              8.26784895688698,
              49.48385215854046
            ],
            [
              8.254235856540248,
              49.4735369859369
            ],
            [
              8.206329982660321,
              49.476009401382726
            ],
            [
              8.144623235848911,
              49.47348337461278
            ],
            [
              8.130456199109517,
              49.444393004138874
            ],
            [
              8.184207786708726,
              49.44272026890897
            ],
            [
              8.27254930011,
              49.4496939870607
            ],
            [
              8.321554336809726,
              49.459195112525634
            ],
            [
              8.343709421360586,
              49.451372989171915
            ],
            [
              8.366866937488595,
              49.4323454360553
            ],
            [
              8.40277547897756,
              49.42094186489035
            ],
            [
              8.430055343450363,
              49.423977897060325
            ],
            [
              8.459409268379773,
              49.44312164651734
            ],
            [
              8.491735444975802,
              49.44388447979
            ],
            [
              8.510387742762873,
              49.43358682291861
            ],
            [
              8.498787550481836,
              49.41704223865503
            ],
            [
              8.495539852263391,
              49.39969232736328
            ],
            [
              8.520374313117884,
              49.404691830513684
            ],
            [
              8.531177219178232,
              49.39535656251509
            ],
            [
              8.526999485918964,
              49.38352716038659
            ],
            [
              8.56649226595519,
              49.38873505134697
            ],
            [
              8.602769094461848,
              49.375744545418854
            ],
            [
              8.60885726020382,
              49.346848708781096
            ],
            [
              8.641307414331209,
              49.34018116795525
            ],
            [
              8.653028970482865,
              49.32309830046253
            ],
            [
              8.70909291220218,
              49.31229231309803
            ],
            [
              8.711880498205431,
              49.34038267976584
            ],
            [
              8.755725692269152,
              49.343056226703425
            ],
            [
              8.821658740696677,
              49.36309854371484
            ],
            [
              8.83347847335665,
              49.39274510521065
            ],
            [
              8.829757874173055,
              49.49985021061855
            ],
            [
              8.80422336940282,
              49.50747338929207
            ],
            [
              8.748405932192526,
              49.5017997361833
            ],
            [
              8.73188936131828,
              49.45907389762888
            ],
            [
              8.70928817502508,
              49.44832528571729
            ],
            [
              8.696851480740605,
              49.4688987841802
            ],
            [
              8.700451766725479,
              49.5065198846691
            ],
            [
              8.713731257143934,
              49.546293794223544
            ],
            [
              8.693653140061826,
              49.562616944802784
            ],
            [
              8.661474836362174,
              49.56682199364306
            ]
          ]
        ]
      }
    }
  }
}

=== public-transport/transport-apis/data/de/gvh-efa.json
{
    "name": "Gro√üraum-Verkehr Hannover (GVH)",
    "coverage": {
        "realtimeCoverage": {
            "area": {
                "coordinates": [
                    [ [ 6.8558, 53.8848 ], [ 6.6065, 52.0076 ], [ 10.7129, 51.0397 ], [ 11.6759, 53.1955 ], [ 9.6178, 53.9532 ], [ 6.8558, 53.8848 ] ]
                ],
                "type": "Polygon"
            },
            "region": [ "DE-NI" ]
        }
    },
    "options": {
        "endpoint": "https://app.efa.de/mdv_server/app_gvh/"
    },
    "supportedLanguages": [ "de", "en" ],
    "type": {
        "efa": true
    }
}

=== public-transport/transport-apis/data/de/bayernfahrplan-efa.json
{
    "name": "Bayern Fahrplan",
    "coverage": {
        "realtimeCoverage": {
            "area": {
                "coordinates": [
                    [ [ 8.7591, 50.5296 ], [ 12.872, 50.66655 ], [ 14.3451, 47.6552 ], [ 9.9063, 46.9968 ], [ 8.7591, 50.5296 ] ]
                ],
                "type": "Polygon"
            },
            "region": [ "DE-BY" ]
        }
    },
    "options": {
        "compactXmlRepsonse": true,
        "endpoint": "https://mobile.defas-fgi.de/beg/"
    },
    "supportedLanguages": [ "de", "en" ],
    "type": {
        "efa": true
    }
}
